//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.28 at 11:00:27 AM IST 
//


package org.wso2.carbon.eventprocessing.executiongenerator.internal.templatestructure.templateconfiguration;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TemplateConfig_QNAME = new QName("", "TemplateConfig");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TemplateConfig }
     * 
     */
    public TemplateConfig createTemplateConfig() {
        return new TemplateConfig();
    }

    /**
     * Create an instance of {@link Parameters }
     * 
     */
    public Parameters createParameters() {
        return new Parameters();
    }

    /**
     * Create an instance of {@link Template }
     * 
     */
    public Template createTemplate() {
        return new Template();
    }

    /**
     * Create an instance of {@link Or }
     * 
     */
    public Or createOr() {
        return new Or();
    }

    /**
     * Create an instance of {@link TemplateWiring }
     * 
     */
    public TemplateWiring createTemplateWiring() {
        return new TemplateWiring();
    }

    /**
     * Create an instance of {@link Templates }
     * 
     */
    public Templates createTemplates() {
        return new Templates();
    }

    /**
     * Create an instance of {@link ConditionParameters }
     * 
     */
    public ConditionParameters createConditionParameters() {
        return new ConditionParameters();
    }

    /**
     * Create an instance of {@link TemplateObject }
     * 
     */
    public TemplateObject createTemplateObject() {
        return new TemplateObject();
    }

    /**
     * Create an instance of {@link OR }
     * 
     */
    public OR createOR() {
        return new OR();
    }

    /**
     * Create an instance of {@link And }
     * 
     */
    public And createAnd() {
        return new And();
    }

    /**
     * Create an instance of {@link AND }
     * 
     */
    public AND createAND() {
        return new AND();
    }

    /**
     * Create an instance of {@link Parameter }
     * 
     */
    public Parameter createParameter() {
        return new Parameter();
    }

    /**
     * Create an instance of {@link DirectParameter }
     * 
     */
    public DirectParameter createDirectParameter() {
        return new DirectParameter();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TemplateConfig }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TemplateConfig")
    public JAXBElement<TemplateConfig> createTemplateConfig(TemplateConfig value) {
        return new JAXBElement<TemplateConfig>(_TemplateConfig_QNAME, TemplateConfig.class, null, value);
    }

}
